service_principals:
  - name: "m365_groups"
    display_name: "sp-tf-m365-groups"
    description: "Service Principal for Microsoft 365 Groups Terraform workspace"
    tags:
      - "terraform"
      - "microsoft365"
      - "groups"
    permissions:
      - id: "19dbc75e-c2e2-444c-a770-ec69d8559fc7"
        type: "Role"
        description: "Directory.ReadWrite.All"
      - id: "62a82d76-70ea-41e2-9197-370581804d09"
        type: "Role"
        description: "Group.ReadWrite.All"
      - id: "9a5d68dd-52b0-4cc2-bd40-abcf44ac3a30"
        type: "Role"
        description: "Application.Read.All"

  - name: "m365_device_management_shared"
    display_name: "sp-tf-device-and-app-management-shared"
    description: "Service Principal for Microsoft 365 Device Management Shared Terraform workspace"
    tags:
      - "terraform"
      - "microsoft365"
      - "device-management"
      - "shared"
    permissions:
      - id: "19dbc75e-c2e2-444c-a770-ec69d8559fc7"
        type: "Role"
        description: "Directory.ReadWrite.All"
      - id: "62a82d76-70ea-41e2-9197-370581804d09"
        type: "Role"
        description: "Group.ReadWrite.All"
      - id: "9a5d68dd-52b0-4cc2-bd40-abcf44ac3a30"
        type: "Role"
        description: "Application.Read.All"
      - id: "e2a3a72e-5f79-4c64-b1b1-878b674786d9"
        type: "Role"
        description: "DeviceManagementConfiguration.ReadWrite.All"
      - id: "243333ab-4d21-40cb-a475-36241daa0842"
        type: "Role"
        description: "DeviceManagementManagedDevices.ReadWrite.All"
      - id: "5b07b0dd-2377-4e44-a38d-703f09a0dc3c"
        type: "Role"
        description: "DeviceManagementApps.ReadWrite.All"

  - name: "m365_device_management_windows"
    display_name: "sp-tf-device-and-app-management-windows"
    description: "Service Principal for Microsoft 365 Windows Device Management Terraform workspace"
    tags:
      - "terraform"
      - "microsoft365"
      - "device-management"
      - "windows"
    permissions:
      - id: "19dbc75e-c2e2-444c-a770-ec69d8559fc7"
        type: "Role"
        description: "Directory.ReadWrite.All"
      - id: "62a82d76-70ea-41e2-9197-370581804d09"
        type: "Role"
        description: "Group.ReadWrite.All"
      - id: "9a5d68dd-52b0-4cc2-bd40-abcf44ac3a30"
        type: "Role"
        description: "Application.Read.All"
      - id: "e2a3a72e-5f79-4c64-b1b1-878b674786d9"
        type: "Role"
        description: "DeviceManagementConfiguration.ReadWrite.All"
      - id: "243333ab-4d21-40cb-a475-36241daa0842"
        type: "Role"
        description: "DeviceManagementManagedDevices.ReadWrite.All"
      - id: "5b07b0dd-2377-4e44-a38d-703f09a0dc3c"
        type: "Role"
        description: "DeviceManagementApps.ReadWrite.All"
      - id: "7438b122-aefc-4978-80ed-43db9fcc7715"
        type: "Role"
        description: "DeviceManagementServiceConfig.ReadWrite.All"
      - id: "dc149144-f292-421e-b185-5953f2e98d7f"
        type: "Role"
        description: "DeviceManagementRBAC.ReadWrite.All"

  - name: "m365_device_management_macos"
    display_name: "sp-tf-device-and-app-management-macos"
    description: "Service Principal for Microsoft 365 macOS Device Management Terraform workspace"
    tags:
      - "terraform"
      - "microsoft365"
      - "device-management"
      - "macos"
    permissions:
      - id: "19dbc75e-c2e2-444c-a770-ec69d8559fc7"
        type: "Role"
        description: "Directory.ReadWrite.All"
      - id: "62a82d76-70ea-41e2-9197-370581804d09"
        type: "Role"
        description: "Group.ReadWrite.All"
      - id: "9a5d68dd-52b0-4cc2-bd40-abcf44ac3a30"
        type: "Role"
        description: "Application.Read.All"
      - id: "e2a3a72e-5f79-4c64-b1b1-878b674786d9"
        type: "Role"
        description: "DeviceManagementConfiguration.ReadWrite.All"
      - id: "243333ab-4d21-40cb-a475-36241daa0842"
        type: "Role"
        description: "DeviceManagementManagedDevices.ReadWrite.All"
      - id: "5b07b0dd-2377-4e44-a38d-703f09a0dc3c"
        type: "Role"
        description: "DeviceManagementApps.ReadWrite.All"
      - id: "7438b122-aefc-4978-80ed-43db9fcc7715"
        type: "Role"
        description: "DeviceManagementServiceConfig.ReadWrite.All"
      - id: "dc149144-f292-421e-b185-5953f2e98d7f"
        type: "Role"
        description: "DeviceManagementRBAC.ReadWrite.All"

  - name: "m365_device_management_android"
    display_name: "sp-tf-device-and-app-management-android"
    description: "Service Principal for Microsoft 365 Android Device Management Terraform workspace"
    tags:
      - "terraform"
      - "microsoft365"
      - "device-management"
      - "android"
    permissions:
      - id: "19dbc75e-c2e2-444c-a770-ec69d8559fc7"
        type: "Role"
        description: "Directory.ReadWrite.All"
      - id: "62a82d76-70ea-41e2-9197-370581804d09"
        type: "Role"
        description: "Group.ReadWrite.All"
      - id: "9a5d68dd-52b0-4cc2-bd40-abcf44ac3a30"
        type: "Role"
        description: "Application.Read.All"
      - id: "e2a3a72e-5f79-4c64-b1b1-878b674786d9"
        type: "Role"
        description: "DeviceManagementConfiguration.ReadWrite.All"
      - id: "243333ab-4d21-40cb-a475-36241daa0842"
        type: "Role"
        description: "DeviceManagementManagedDevices.ReadWrite.All"
      - id: "5b07b0dd-2377-4e44-a38d-703f09a0dc3c"
        type: "Role"
        description: "DeviceManagementApps.ReadWrite.All"
      - id: "7438b122-aefc-4978-80ed-43db9fcc7715"
        type: "Role"
        description: "DeviceManagementServiceConfig.ReadWrite.All"
      - id: "dc149144-f292-421e-b185-5953f2e98d7f"
        type: "Role"
        description: "DeviceManagementRBAC.ReadWrite.All"

  - name: "m365_device_management_ios_ipados"
    display_name: "sp-tf-device-and-app-management-ios-ipados"
    description: "Service Principal for Microsoft 365 iOS/iPadOS Device Management Terraform workspace"
    tags:
      - "terraform"
      - "microsoft365"
      - "device-management"
      - "ios-ipados"
    permissions:
      - id: "19dbc75e-c2e2-444c-a770-ec69d8559fc7"
        type: "Role"
        description: "Directory.ReadWrite.All"
      - id: "62a82d76-70ea-41e2-9197-370581804d09"
        type: "Role"
        description: "Group.ReadWrite.All"
      - id: "9a5d68dd-52b0-4cc2-bd40-abcf44ac3a30"
        type: "Role"
        description: "Application.Read.All"
      - id: "e2a3a72e-5f79-4c64-b1b1-878b674786d9"
        type: "Role"
        description: "DeviceManagementConfiguration.ReadWrite.All"
      - id: "243333ab-4d21-40cb-a475-36241daa0842"
        type: "Role"
        description: "DeviceManagementManagedDevices.ReadWrite.All"
      - id: "5b07b0dd-2377-4e44-a38d-703f09a0dc3c"
        type: "Role"
        description: "DeviceManagementApps.ReadWrite.All"
      - id: "7438b122-aefc-4978-80ed-43db9fcc7715"
        type: "Role"
        description: "DeviceManagementServiceConfig.ReadWrite.All"
      - id: "dc149144-f292-421e-b185-5953f2e98d7f"
        type: "Role"
        description: "DeviceManagementRBAC.ReadWrite.All"

  - name: "m365_device_management_linux"
    display_name: "sp-tf-device-and-app-management-linux"
    description: "Service Principal for Microsoft 365 Linux Device Management Terraform workspace"
    tags:
      - "terraform"
      - "microsoft365"
      - "device-management"
      - "linux"
    permissions:
      - id: "19dbc75e-c2e2-444c-a770-ec69d8559fc7"
        type: "Role"
        description: "Directory.ReadWrite.All"
      - id: "62a82d76-70ea-41e2-9197-370581804d09"
        type: "Role"
        description: "Group.ReadWrite.All"
      - id: "9a5d68dd-52b0-4cc2-bd40-abcf44ac3a30"
        type: "Role"
        description: "Application.Read.All"
      - id: "e2a3a72e-5f79-4c64-b1b1-878b674786d9"
        type: "Role"
        description: "DeviceManagementConfiguration.ReadWrite.All"
      - id: "243333ab-4d21-40cb-a475-36241daa0842"
        type: "Role"
        description: "DeviceManagementManagedDevices.ReadWrite.All"
      - id: "5b07b0dd-2377-4e44-a38d-703f09a0dc3c"
        type: "Role"
        description: "DeviceManagementApps.ReadWrite.All"
      - id: "7438b122-aefc-4978-80ed-43db9fcc7715"
        type: "Role"
        description: "DeviceManagementServiceConfig.ReadWrite.All"
      - id: "dc149144-f292-421e-b185-5953f2e98d7f"
        type: "Role"
        description: "DeviceManagementRBAC.ReadWrite.All"

  - name: "m365_device_management_windows_365"
    display_name: "sp-tf-device-and-app-management-windows-365"
    description: "Service Principal for Microsoft 365 Windows 365 Device Management Terraform workspace"
    tags:
      - "terraform"
      - "microsoft365"
      - "device-management"
      - "windows-365"
    permissions:
      - id: "19dbc75e-c2e2-444c-a770-ec69d8559fc7"
        type: "Role"
        description: "Directory.ReadWrite.All"
      - id: "62a82d76-70ea-41e2-9197-370581804d09"
        type: "Role"
        description: "Group.ReadWrite.All"
      - id: "9a5d68dd-52b0-4cc2-bd40-abcf44ac3a30"
        type: "Role"
        description: "Application.Read.All"
      - id: "e2a3a72e-5f79-4c64-b1b1-878b674786d9"
        type: "Role"
        description: "DeviceManagementConfiguration.ReadWrite.All"
      - id: "243333ab-4d21-40cb-a475-36241daa0842"
        type: "Role"
        description: "DeviceManagementManagedDevices.ReadWrite.All"
      - id: "5b07b0dd-2377-4e44-a38d-703f09a0dc3c"
        type: "Role"
        description: "DeviceManagementApps.ReadWrite.All"
      - id: "7438b122-aefc-4978-80ed-43db9fcc7715"
        type: "Role"
        description: "DeviceManagementServiceConfig.ReadWrite.All"
      - id: "dc149144-f292-421e-b185-5953f2e98d7f"
        type: "Role"
        description: "DeviceManagementRBAC.ReadWrite.All"

# Microsoft Graph API settings
graph:
  resource_app_id: "00000003-0000-0000-c000-000000000000"  # Microsoft Graph
  scope: ["https://graph.microsoft.com/.default"]

# Application settings
settings:
  app_role_assignment_required: false
  create_secrets: true
  secret_expiry_months: 12