name: "🏗️ Build Container Image"

on:
  push:
    branches:
      - main
    paths:
      - 'scripts/**'
      - './docker/golang/Dockerfile'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push utils image
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          file: ./docker/golang/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/go-utils-tf-microsoft365:latest