on:
  push:
    branches:
    - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    name: '🔖 Release Please'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/create-github-app-token@v2.0.6
      id: app-token
      with:
        app-id: ${{ secrets.RPM_APP_ID }}
        private-key: ${{ secrets.RPM_APP_PRIVATE_KEY }}

    - uses: googleapis/release-please-action@v4
      with:
        token: ${{ steps.app-token.outputs.token }}
        release-type: simple