name: Add PR Comment

on:
  workflow_call:
    inputs:
      artifact-name:
        required: true
        type: string

      target-pr-number:
        required: true
        type: number
        
jobs:

  update-pr:
    runs-on: ubuntu-latest
    permissions:
      packages: read
      pull-requests: write
      contents: write
      
    container:
      image: ghcr.io/${{ github.repository }}/python:latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        
      
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download artifact
        id: download-artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}

      - name: Run pr update python utility
        run: python .github/scripts/update_pr.py
        env:
          REPO: ${{ github.repository }}
          ARTIFACT_PATH: ${{ steps.download-artifact.outputs.download-path }}/${{vars.ARTIFACT_FN}}
          TARGET_PR_NUMBER: ${{ inputs.target-pr-number}}