name: '💬 Add TF Plan Output to PR'

on:
  workflow_call:
    inputs:
      artifact-name:
        required: true
        type: string

      target-pr-number:
        required: true
        type: number
        
jobs:

  update-pr:
    runs-on: ubuntu-latest
    permissions:
      packages: read
      pull-requests: write
      contents: write
      
    container:
      image: ghcr.io/${{ github.repository }}/go-utils-tf-microsoft365:latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        
      
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.2.2

      - name: Download artifact
        id: download-artifact
        uses: actions/download-artifact@v4.3.0
        with:
          name: ${{ inputs.artifact-name }}

      - name: Run PR updater utility
        run: |
          ./pr-updater
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          ARTIFACT_PATH: ${{ steps.download-artifact.outputs.download-path }}/${{ vars.TF_PLAN_OUTPUT }}
          TARGET_PR_NUMBER: ${{ inputs.target-pr-number }}